version: 2.1

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Create NPMRC
          command: echo $NPM_TOKEN > ~/repo/.npmrc
      - run:
          name: NPM Install
          command: npm install
       - run:
          name: NPM Test
          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.13.0
    steps:
      - attach_workspace:
          at: ~/repo
#      - run:
#          name: Set registry URL
#          command: npm set registry https://packagecloud.io/armando/node-test-package/npm/
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2.1
  test:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
